### ISSUE TITLE
How do I use this code

### ISSUE THREAD

**Issue by linyigang2022** [TongChiYip/LosslessCodec#2]
How do I use this code?

**Comment by ZhiyeTang** [comment]
Sorry, I've forgotten to translate the README.md file into English. This issue is going to be solved soon. Thanks a lot!

**Comment by linyigang2022** [comment]
> Sorry, I've forgotten to translate the README.md file into English. This issue is going to be solved soon. Thanks a lot!

Thank you for your answers!!!
